export const JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET';
export const JWT_ACCESS_TOKEN_EXP_TIME = 'JWT_ACCESS_TOKEN_EXP_TIME';
export const JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET';
export const JWT_REFRESH_TOKEN_EXP_TIME = 'JWT_REFRESH_TOKEN_EXP_TIME';

export const ACCESS_COOKIE_NAME = 'token'
export const REFRESH_COOKIE_NAME = 'refresh'

export const JWT_REFRESH_TOKEN_STRATEGY = 'jwt-refresh-token'
export const JWT_ACCESS_TOKEN_STRATEGY = 'jwt'
export const LOCAL_STRATEGY = 'local'